### ISSUE TITLE
Swagger UI "Try it out" feature does not work when running API on the OSF

### ISSUE THREAD

**Issue by samanehsan** [brianjgeiger/osf.io#46]
Steps: 
1) Go to http://localhost:5000/api/v2/docs/
2) Click on "nodes" to list its operations
3) Click on "GET"
4) Click "Try it out!"

Expected:
I get the json response for the nodes endpoint

Actual: 
I get taken to a page that has the message: "Email SupportContactHelp/SupportContact"

**Comment by samanehsan** [comment]
In order for the "Try it out" feature to work when running the api through the OSF, the `SWAGGER_SETTINGS` `api_path` must be set to `"/api/v2/"`. However, if we are running the apiserver, the api_path must be the default `""`. 

We need a way in the settings to know whether the API is being run through the OSF or on its own so that the correct path can be used. I previously set an `API_SERVER_PORT` on the OSF settings that defaults to 8000 when running the API, but gets changed to 5000 when running the OSF. I tried to use this to conditionally set the `api_path` but the django settings only import the default `API_SERVER_PORT`.

**Comment by samanehsan** [comment]
I'm going to table this for now and work on other things, so anyone is welcome to look into this.

**Comment by brianjgeiger** [comment]
What makes this the most difficult is that the SWAGGER_SETTINGS is required by the django-swagger app, which we don't have control over. Because django settings are immutable, we can't get the information into the right form before everything is set. The best way I've seen around this, short of submitting a PR to django swagger, is to replace the django settings with something more dynamic so that we have the ability to change them runtime. However, that's a lot of work. For now, because it only affects one of two types of documentation presentation format, and only on the internal-only method of access, I think if we had to launch like this, we could do so.

**Comment by brianjgeiger** [comment]
http://stackoverflow.com/questions/6528723/changing-django-settings-at-runtime

**Comment by samanehsan** [comment]
Once we no longer allow the api to run on the osf server (with PR #63), this will no longer be a problem.

**Comment by samanehsan** [comment]
Closing this since we can no longer run the api on the osf server.
