### ISSUE TITLE
Add middleware to tear close mongo connection after every request

### ISSUE THREAD

**Issue by sloria** [brianjgeiger/osf.io#52]
Similar to the handlers we have set up here: https://github.com/CenterForOpenScience/osf.io/blob/db8cefa7d20cf22cbf80f2ab16317bb8cc52e71c/framework/mongo/handlers.py#L28-42 , we will need a middleware to disconnect from mongo after every request.

**Comment by brianjgeiger** [comment]
Isn't this happening? It looks like the current middleware is working through framework.transactions.commands, and commands is using the handler for pymongo, which is the thing you quoted above. Or am I misunderstanding?

**Comment by sloria** [comment]
It is closing transactions, but not the database client; see the code that I linked to.

**Comment by brianjgeiger** [comment]
No, I see the code you linked to, but I haven't figured out yet how that gets called in the existing code. I'm tracing it through on the OSF side now. I see there are callbacks attached to the app. Which looks to be a flask thing? Ah, okay, yes. Flask Signals. 

Like #21, it's tricky because I'm trying to take two systems that I don't know how either works and make one work more like the other. I should get there eventually, I presume.
